version: '3'

services:

  snake-database:
    image: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: p@S5w0Rd
      POSTGRES_DB: snake
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - server-database

  snake-server:
    build: snake-server
    container_name: server
    ports:
      - 8080:8080
    networks:
      - webapp-server
      - server-database

  snake-webapp:
    build: snake-client
    container_name: webapp
    ports:
      - 4200:80
    depends_on:
      - snake-server
    networks:
      - webapp-server

networks:
  webapp-server:
  server-database:

volumes:
  database-data:
