version: '3'

services:

  snake-server:
    build: snake-server
    container_name: server
    ports:
      - 8080:8080
    networks:
      - webapp-server

  snake-webapp:
    build: snake-client
    container_name: webapp
    ports:
      - 4200:80
    depends_on:
      - snake-server
    networks:
      - webapp-server

networks:
  webapp-server:
